// <auto-generated />

using DevBridgeAPI.Models;
using DevBridgeAPI.Repository.Selector;
using Microsoft.Owin.Security.OAuth;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;

namespace DevBridgeAPI.Helpers
{
    public class AuthorizationServerProvider : OAuthAuthorizationServerProvider
    {
#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously
        public override async Task ValidateClientAuthentication(OAuthValidateClientAuthenticationContext context)
#pragma warning restore CS1998 // Async method lacks 'await' operators and will run synchronously
        {
            context.Validated();
        }

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously
        public override async Task GrantResourceOwnerCredentials(OAuthGrantResourceOwnerCredentialsContext context)
#pragma warning restore CS1998 // Async method lacks 'await' operators and will run synchronously
        {
            var identity = new ClaimsIdentity(context.Options.AuthenticationType);

            var userSelector = new UsersSelector();

            var userData = (User) userSelector.SelectOneRow(context.UserName, context.Password);
            if (userData != null)
            {
                identity.AddClaim(new Claim(ClaimTypes.Role, userData.Role));
                identity.AddClaim(new Claim(ClaimTypes.Name, userData.Email));
                context.Validated(identity);
            }
            else
            {
                context.SetError("invalid_grant", "Provided username and password is incorrect");
                context.Rejected();
            }
        }
    }
}