// <auto-generated/>

using System;
using System.Threading.Tasks;
using System.Web.Http;
using DevBridgeAPI.Helpers;
using DevBridgeAPI.Repository.Dao;
using Microsoft.Owin;
using Microsoft.Owin.Security.OAuth;
using Owin;

[assembly: OwinStartup(typeof(DevBridgeAPI.App_Start.Startup))]

namespace DevBridgeAPI.App_Start
{
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            app.UseCors(Microsoft.Owin.Cors.CorsOptions.AllowAll);

            var myProvider = new AuthorizationServerProvider();
            OAuthAuthorizationServerOptions options = new OAuthAuthorizationServerOptions
            {
                AllowInsecureHttp = true,
                TokenEndpointPath = new PathString("/token"),
                AccessTokenExpireTimeSpan = TimeSpan.FromMinutes(60),
                Provider = myProvider
            };
            app.UseOAuthAuthorizationServer(options);
            app.UseOAuthBearerAuthentication(new OAuthBearerAuthenticationOptions());

            HttpConfiguration config = new HttpConfiguration();
            WebApiConfig.Register(config);

            GlobalConfiguration.Configuration.Filters
                .Add(new Helpers.Filters.GeneralExceptionAttribute(new ExceptionLoggerToDB(new ExceptionDao())));
            //.Add(new Helpers.Filters.GeneralExceptionAttribute(new ExceptionLoggerToFile()));
        }
    }
}
